/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CartSidebar: typeof import('./components/CartSidebar.vue')['default']
    CategorySidebar: typeof import('./components/CategorySidebar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    Receipt: typeof import('./components/Receipt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
